# Configuration file

port: 8080

InitialToDos:
  - Id:    "daily.garbage"
    Title: "Take out the garbage"
  - Id:    "daily.milk"
    Title: "Shop for milk"
  - Id:    "daily.bread"
    Title: "Shop for bread"
  - Id:    "say.hello"
    Title: "Say hello4"
